### ISSUE TITLE
Errors when parsing submission data

### ISSUE THREAD

**Issue by jjpete24** [vmray/vmray-misp-feed#1]
Hello,

I've setup and run the script, and it works great for submissions that are older than a year.  But for newer submissions, I get key errors such as this one:

`Traceback (most recent call last):
  File "src/feed.py", line 117, in <module>
    main()
  File "src/feed.py", line 113, in main
    vmray_feed.update_feed()
  File "src/feed.py", line 87, in update_feed
    event = parser.parse(submission_id)
  File "/opt/vmray-misp-feed/src/lib/vmray/parser.py", line 1121, in parse
    for artifact in report.artifacts():
  File "/opt/vmray-misp-feed/src/lib/vmray/parser.py", line 866, in artifacts
    domain = self._resolve_ref(ref_domain)["domain"]
KeyError: 'domain'`

**Comment by ZLT-ops** [comment]
Submitted a PR to fix the issues
