### ISSUE TITLE
Error parsing IP address in submission data

### ISSUE THREAD

**Issue by faustus25** [vmray/vmray-misp-feed#4]
Feed script fails when parsing certain submission data for IP address.

` feed.py:     INFO | Processing submission 1123416
Traceback (most recent call last):
  File "/opt/vmray-misp-feed/src/feed.py", line 117, in <module>
    main()
  File "/opt/vmray-misp-feed/src/feed.py", line 113, in main
    vmray_feed.update_feed()
  File "/opt/vmray-misp-feed/src/feed.py", line 87, in update_feed
    event = parser.parse(submission_id)
  File "/opt/vmray-misp-feed/src/lib/vmray/parser.py", line 1112, in parse
    for artifact in report.artifacts():
  File "/opt/vmray-misp-feed/src/lib/vmray/parser.py", line 753, in artifacts
    artifact.ips.append(ip_address["ip_address"])
KeyError: 'ip_address'`

**Comment by faustus25** [comment]
This commit to parser.py resolves the issue so update the existing parser script to this commit: https://github.com/vmray/vmray-misp-feed/blob/95bc940fff831079ae548bfc50536e918b4905d8/src/lib/vmray/parser.py
